### ISSUE TITLE
Exports not showing

### ISSUE THREAD

**Issue by russdeffner** [hotosm/osm-export-tool2#186] opened 2017-06-05 17:42 UTC
On the exports tab I don't see my exports anymore since we had the issue with amelia, think that was end of April. I can still get to them via direct URL, such as http://export.hotosm.org/en/exports/af5e4605-c1c4-456b-a784-31192bf81969/ so they're there, just not on the list.  Related: full list of exports seems to only show back to beginning of May.

**Comment by bdon** [comment] 2017-06-06 02:56
Hmm, I can't reproduce this yet. @russdeffner can you attach a screenshot and also try unchecking the "My Exports" checkbox in the bottom left of http://export.hotosm.org/en/exports/ ?

**Comment by russdeffner** [comment] 2017-06-07 03:52
![exports](https://user-images.githubusercontent.com/6763645/26861612-3211cb38-4b02-11e7-9170-cedc82bc5446.PNG)
In top image it shows nothing for my exports.
![exports2](https://user-images.githubusercontent.com/6763645/26861615-342f2bfe-4b02-11e7-8417-2a64e9a12627.PNG)
In this image it shows the last two exports in the list, i.e. nothing before May 6th.

**Comment by bdon** [comment] 2017-06-28 02:41
@russdeffner I finally discovered the cause of this. If you click the "Filter Exports" button in the top left, it will default the date filter to the past month. Moving this earlier will expose more exports.

That should be a workable solution on the existing export tool - won't change it as-is as we're focusing on developing the new version.

**Closed by bdon** 2017-06-28 02:41 UTC

**Comment by russdeffner** [comment] 2017-06-29 23:06
@bdon ah, thanks Brandon, didn't think there'd be a filter by default but now I know.
