### ISSUE TITLE
Map doesn't always zoom to export extent on clone job

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#45] opened 2015-09-16 14:31 UTC
Appears to be ajax callback issue.

**Comment by bjohare** [comment] 2015-09-16 15:03
Difficult to reproduce.

**Comment by mataharimhairi** [comment] 2015-10-05 16:40
Unfortunately I just reproduced this when I tried to clone the export 'Test Lesotho' created by 'geofrizz'. When it takes you to the 'Create Wizard', the map was zoomed out with the blue bounding box surrounding the area of interest. Although this doesn't always happen, as the map was zoomed into the area of interest the second time I tried to clone the same export.

**Comment by mataharimhairi** [comment] 2016-01-19 14:44
Doesn't seem to be happening now, or at least during the last couple of weeks since I've been using it. Going to close this issue for now.

**Closed by mataharimhairi** 2016-01-19 14:44 UTC
Labels: bug, high, Live Release
