### ISSUE TITLE
Not downloading all the data in dataset

### ISSUE THREAD

**Issue by jwitcoski** [hotosm/osm-export-tool2#84] opened 2015-10-06 18:19 UTC
Cool slick interface!!  However when I selected a small island to download the data of I only got a few polygons and not the whole dataset.  What am I doing wrong?  Should I have zoomed in closer? 

http://export.hotosm.org/exports/73a43cc8-7b49-448b-adb0-7e8e082f0368/ 

![captureosm](https://cloud.githubusercontent.com/assets/5134087/10317939/dd182cb0-6c34-11e5-90a2-e92f5f376a0f.JPG)

**Comment by PaulUithol** [comment] 2015-10-12 21:44
Looks like this area - https://www.openstreetmap.org/#map=12/10.9309/-65.3173 ?

Had a look at in JOSM and at the shapefiles - the dataset is a lot larger than expected, a lot of they ways are incredibly detailed and could use a dose of "Simplify way". There's a bunch of untagged ways as well. But it looks like the detailed ones do get exported properly.

@bjohare, could try to see why for example "Way: 12193875, Data set: 1a4e9738, Edited at: 2015-07-05T06:14:42Z" didn't get exported? The only difference I can tell with ones that do get exported is that, in addition to `natural=coastline`, it has additional tags `converted_by=mikes` and `source=PGS`.

**Comment by jwitcoski** [comment] 2015-10-12 22:21
sorry, forgot to give you the coordinates.

**Comment by bjohare** [comment] 2015-10-16 10:58
I've tried this export again using the OSM Data Model and it looks to me as if all features are exported correctly see http://export.hotosm.org/downloads/ce80fad5-0185-4204-a19c-84c75761c80f/testtest_shp.zip. The OSM model includes natural=coastline as well as administrative boundaries which are missing from the HDM model. This why I've asked for someone from the community to check these models. The HDM model comes from http://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Tags/HDM_preset and https://github.com/hotosm/presets/blob/master/HDM.xml. The feature selection trees are generated from HDM.xml (with some landuse additions of my own) but is this the behaviour we want or does the HDM model need to be updated/amended?

**Comment by PaulUithol** [comment] 2015-10-16 11:02
I know @bjohare - I've taken a look, will do more in depth when I have the time, but both look basically fine to me. Not that much difference, actually. My point above was that this doesn't seem to the differentiating factor - some features with only the `natural=coastline` tag are in the original export, while others with extra tags aren't?

**Comment by bgirardot** [comment] 2015-10-16 11:13
The HDM needs review as well.

**Comment by mataharimhairi** [comment] 2015-11-05 06:04
This has been a requirement floating round for a while. I will add it to the agenda for the next Activation WG meeting to discuss it and start to put something together to address it. Will add it to this issue once we have a 'working' solution going.

**Comment by bdon** [comment] 2017-06-26 16:17
Duplicate of #79 - we have a spreadsheet to collect relevant tag and filter information for each of the tag tree items.

**Closed by bdon** 2017-06-26 16:17 UTC
Labels: Bug, High
