### ISSUE TITLE
Bug: get empty polygon and line layers

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#136] opened 2017-02-03 20:23 UTC
Eg from http://export.hotosm.org/en/exports/1082ca10-c404-4560-bc6d-c3df0ca5c0bf/
Whatever the SIG file format, only the points are correctly extracted

**Comment by bdon** [comment] 2017-02-22 23:17
may be a duplicate of #129

**Comment by bdon** [comment] 2017-03-01 20:17
This should be resolved by fix applied in #129. I have re-ran the export linked above: 

http://export.hotosm.org/en/exports/1082ca10-c404-4560-bc6d-c3df0ca5c0bf/

The Shapefiles created include polygons and lines:

<img width="964" alt="screen shot 2017-03-01 at 3 16 06 pm" src="https://cloud.githubusercontent.com/assets/77501/23479312/117ad142-fe92-11e6-9904-bd1bd23b3617.png">

@severinmenard please inspect the new result of the export job and re-open this issue if there is still missing data. Closing for now.

**Closed by bdon** 2017-03-01 20:17 UTC

**Comment by severinmenard** [comment] 2017-03-07 14:21
Works for me as well now
