### ISSUE TITLE
When reviewing an existing export it would be good to easily see the features selected for export

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#27] opened 2015-09-02 21:51 UTC
When I look at an existing export, I don't see any way to see what features are selected. In the few exports I made, there is a "Josm presets.xml" file that I think lists what features are selected, but not all exports have that file.

That would really be helpful as we want to encourage people to re-use existing exports I would think.

**Comment by bjohare** [comment] 2015-09-04 11:12
There are 258 possible feature selections in the HDM model, so it's a question of how to display this without cluttering the UI....?

**Comment by bgirardot** [comment] 2015-09-04 11:16
I was thinking the same "tree" view (with expand and collapse all options) just not a selectable tree view, basically display only.

**Comment by bgirardot** [comment] 2015-09-04 13:31
Another simpler option is just a text list that gets written to a file, basically a simplified version of the .xml file that gets generated for presets. And it gets listed as one of the file types to download, but it is for informational purposes only. But I really think we need to see what is selected on a job to know if we can reuse it or not.

So I think the tree list view is good, the text file is good, but if either of those are too complicated, how about at least letting us know if the all "HDM Model" or all "OSM Model" options were chosen, as I bet one of those "every item" will be the choice for the vast majority of export jobs.

**Comment by mataharimhairi** [comment] 2015-09-06 08:39
Perhaps we could have the feature tags selected from the tree saved by default as a 'Custom JOSM Preset (XML)' file provided along with the other export file formats, so the user can check the features from there before re-running, cloning, etc.

**Comment by mataharimhairi** [comment] 2015-09-22 08:12
Brian has added a button (Features) at the bottom of the Export Summary page, which when clicked lists all the features selected on the tree tag. This is simply a duplicate of the tree selection during the create export phase.

<img width="677" alt="features" src="https://cloud.githubusercontent.com/assets/8972913/10013518/a32914ec-6144-11e5-8845-4a8ed3e0262e.png">

**Closed by mataharimhairi** 2015-09-22 08:12 UTC
Labels: Pending Review
