### ISSUE TITLE
At least one export format must be selected: not clear if you missed it

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#56] opened 2015-09-26 20:25 UTC
Actually no obligation if you did not click on the tab. If you missed this step, you get an Invalid form error msg when clicking on the Create Export button, what is not explicit

**Comment by bjohare** [comment] 2015-09-28 07:13
Can't reproduce this. The user should not be able to navigate away from the format selection tab without choosing one. Is this on Create Export or Clone Export? Maybe you need to refresh your browser cache? Hit F5?

**Comment by severinmenard** [comment] 2015-09-28 07:19
To reproduce it:
Click on Create
Fill the title and description
Select Export area
Click on Tree Tag and choose whatever you want
Click on Preset file and do whatever you want or Skip it
Click on Export Detail and tick on checkbox

then if you click on the Create export button you will get the 'Invalid form' message, because you did not process the File formats step. As I mentioned in my previous text: Actually no obligation if you did not click on the [File formats] tab.

**Comment by bjohare** [comment] 2015-09-28 07:28
Thanks Severin, yes can confirm that's a bug.

**Comment by bjohare** [comment] 2015-10-05 14:28
Simplest solution is to disable the 'Tree Tag', 'Preset File' and 'Export Details' tabs until the user has completed the 'Describe Export' and 'File Formats' tabs. I still think there should be a 'Next' button on the 'Describe Export' and 'File Formats' tabs to emphasise the 'wizard' type interface.. ie the user must click though the tabs in order..

**Comment by bgirardot** [comment] 2015-10-05 15:17
I think one of the recent improvements was to add a better error message when you could click create export button, but it would fail, now the error message tells you what is wrong instead of just "invalid"

What I don't understand is when the create button is inactivated, why we can't indicate to the user why it is inactivated.

I am not sure of the need to restrict users from the different tabs or why we would require them to step through tabs in order if we could collect the reasons why we can't create the export and let the user know on that "create export" tab or maybe the tab titles themselves could indicate the tab still needs info filled out like I suggest below.

If we do require the user to go through tags in order or can't use some tabs until other are filled out, there probably needs to be an indication of that in the 'tab' display, like turn completed ones green, errored ones red or not accessible ones greyed out or something.

**Comment by mataharimhairi** [comment] 2016-01-18 17:46
https://github.com/hotosm/osm-export-tool2/issues/24

**Comment by mataharimhairi** [comment] 2016-01-19 14:33
Wanting to close this issue as the initial request has been addressed. There is now an error message ('At least one export format must be selected') provided at the bottom of the 'File Formats' tab and the text is highlighted in red.

Want to make sure the last comments by @bjohare and @bgirardot are also considered and addressed. Perhaps these could be combined so that a 'Next' button is added to the bottom of the tab in red until all the required actions are completed and then they turn green and can be selected.

**Comment by mataharimhairi** [comment] 2016-01-19 16:45
Initial issue address. Opened new ticket for later comments: 

https://github.com/hotosm/osm-export-tool2/issues/112

**Closed** 2016-01-19 17:11 UTC
Labels: Bug, High, Pending Review
